### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by abnnim** [leogout/rasper-ducky#24] opened 2024-11-07 06:03 UTC

**Comment by abnnim** [comment] 2024-11-07 06:04
in the photo only code.py is removed

**Comment by abnnim** [comment] 2024-11-07 06:08
sorry. pico 2, but i have just pico

**Comment by leogout** [comment] 2024-11-07 07:10
Hello @abnnim, it should work on raspberry pico as well. Can you describe the issue ? Do you have logs of the error ? See the documentation for how to read logs produced by the raspberry pico.

**Comment by abnnim** [comment] 2024-11-07 08:15
ok. @leogout you can use google translate
![image](https://github.com/user-attachments/assets/f3aee9ef-2f1e-4ba4-9009-af44789a747c)

**Comment by abnnim** [comment] 2024-11-07 08:24
none of the programs work, but apparently it's a library issue, I don't know. But for example, dbisu pico-ducky works fine

**Comment by abnnim** [comment] 2024-11-08 05:29
need more information? @leogout

**Comment by leogout** [comment] 2024-11-08 10:04
Thanks for your answer, yes could you give me the DuckyScript you're trying to run ?

**Comment by abnnim** [comment] 2024-11-08 11:25
it is the same as in the example. any other scripts do not work either.


DEFINE #COUNT 3

FUNCTION open_powershell()
    GUI R
    STRINGLN powershell
END_FUNCTION

FUNCTION hello_world()
    $x = 0
    WHILE ($x < #COUNT)
        DELAY 500
        STRING Hello, World!
        SPACE
        $x = $x + 1
    END_WHILE
END_FUNCTION

open_powershell()
DELAY 1000
hello_world()

**Comment by leogout** [comment] 2024-11-08 14:01
Thanks for reporting the issue, there is indeed a bug in the program, I am looking into it now. I'll push a fix shortly.

**Comment by leogout** [comment] 2024-11-08 14:06
I see what the problem is, for now you can add an \n at the end of your payload to avoid this. Add an empty line at the end of the payload.dd file. I'll fix the lexer now

**Comment by leogout** [comment] 2024-11-08 14:23
It should be fixed now 👍 thanks again for your feedback

**Closed** 2024-11-11 20:26 UTC
Labels: bug

**Comment by abnnim** [comment] 2024-11-16 13:01
Sorry for the long reply. I'll check the fix tomorrow.

**Comment by abnnim** [comment] 2024-11-20 14:06
Very good! But the letter W is displayed as Z
